package com.tgame.ninja.model;

import com.tgame.ninja.server.ServerController;

public class TaskTemplate {

    public short taskId;

    public String[] name;

    public String[][] subNames;

    public String[][] des;

    public short[] counts;

    public String[][][] questions;

    public int[] results;

    public String[] sayGet;

    public String[] detail;

    public TaskTemplate(short taskId, String[] name, String[] sayGet, String[][] subNames, String[][] des, short[] counts, String[][][] questions, int[] results, String[] detail) {
        this.taskId = taskId;
        this.name = name;
        this.sayGet = sayGet;
        this.subNames = subNames;
        this.des = des;
        this.counts = counts;
        this.questions = questions;
        this.results = results;
        this.detail = detail;
    }

    public static void loadAllTask() {
        ServerController.taskTemplates.add(new TaskTemplate((short) 0, new String[]{ Alert_VN.TASK_1, Alert_EN.TASK_1 }, new String[]{ Alert_VN.TASK_2, Alert_EN.TASK_2 }, new String[][]{ Alert_VN.TASK_DES1, Alert_EN.TASK_DES1 }, new String[][]{ Alert_VN.TASK_DES2, Alert_EN.TASK_DES2 }, null, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 1, new String[]{ Alert_VN.TASK_3, Alert_EN.TASK_3 }, new String[]{ Alert_VN.TASK_4, Alert_EN.TASK_4 }, new String[][]{ Alert_VN.TASK_DES3, Alert_EN.TASK_DES3 }, new String[][]{ Alert_VN.TASK_DES4, Alert_EN.TASK_DES4 }, null, new String[][][] { Alert_VN.TASK_ASK1, Alert_EN.TASK_ASK1 }, new int[]{ 1, 0, 1, 2, 0 }, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 2, new String[]{ Alert_VN.TASK_5, Alert_EN.TASK_5 }, new String[]{ Alert_VN.TASK_6, Alert_EN.TASK_6 }, new String[][]{ Alert_VN.TASK_DES5, Alert_EN.TASK_DES5 }, new String[][]{ Alert_VN.TASK_DES6, Alert_EN.TASK_DES6 }, new short[]{ -1, 10, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 3, new String[]{ Alert_VN.TASK_7, Alert_EN.TASK_7 }, new String[]{ Alert_VN.TASK_8, Alert_EN.TASK_8 }, new String[][]{ Alert_VN.TASK_DES7, Alert_EN.TASK_DES7 }, new String[][]{ Alert_VN.TASK_DES8, Alert_EN.TASK_DES8 }, new short[]{ 2, -1, 20, 10, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE1, Alert_EN.TASK_NOTE1 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 4, new String[]{ Alert_VN.TASK_9, Alert_EN.TASK_9 }, new String[]{ Alert_VN.TASK_10, Alert_EN.TASK_10 }, new String[][]{ Alert_VN.TASK_DES9, Alert_EN.TASK_DES9 }, new String[][]{ Alert_VN.TASK_DES10, Alert_EN.TASK_DES10 }, new short[]{ -1, 2, 2, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE2, Alert_EN.TASK_NOTE2 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 5, new String[]{ Alert_VN.TASK_11, Alert_EN.TASK_11 }, new String[]{ Alert_VN.TASK_12, Alert_EN.TASK_12 }, new String[][]{ Alert_VN.TASK_DES11, Alert_EN.TASK_DES11 }, new String[][]{ Alert_VN.TASK_DES12, Alert_EN.TASK_DES12 }, new short[]{ -1, 15, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE3, Alert_EN.TASK_NOTE3 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 6, new String[]{ Alert_VN.TASK_13, Alert_EN.TASK_13 }, new String[]{ Alert_VN.TASK_14, Alert_EN.TASK_14 }, new String[][]{ Alert_VN.TASK_DES13, Alert_EN.TASK_DES13 }, new String[][]{ Alert_VN.TASK_DES14, Alert_EN.TASK_DES14 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE4, Alert_EN.TASK_NOTE4 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 7, new String[]{ Alert_VN.TASK_15, Alert_EN.TASK_15 }, new String[]{ Alert_VN.TASK_16, Alert_EN.TASK_16 }, new String[][]{ Alert_VN.TASK_DES15, Alert_EN.TASK_DES15 }, new String[][]{ Alert_VN.TASK_DES16, Alert_EN.TASK_DES16 }, null, new String[][][] { Alert_VN.TASK_ASK2, Alert_EN.TASK_ASK2 }, new int[]{ -1, 1, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0, 1, 2, 2, 1 }, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 8, new String[]{ Alert_VN.TASK_17, Alert_EN.TASK_17 }, new String[]{ Alert_VN.TASK_18, Alert_EN.TASK_18 }, new String[][]{ Alert_VN.TASK_DES17, Alert_EN.TASK_DES17 }, new String[][]{ Alert_VN.TASK_DES18, Alert_EN.TASK_DES18 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE5, Alert_EN.TASK_NOTE5 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 9, new String[]{ Alert_VN.TASK_19, Alert_EN.TASK_19 }, new String[]{ Alert_VN.TASK_20, Alert_EN.TASK_20 }, new String[][]{ Alert_VN.TASK_DES19, Alert_EN.TASK_DES19 }, new String[][]{ Alert_VN.TASK_DES20, Alert_EN.TASK_DES20 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE6, Alert_EN.TASK_NOTE6 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 10, new String[]{ Alert_VN.TASK_21, Alert_EN.TASK_21 }, new String[]{ Alert_VN.TASK_22, Alert_EN.TASK_22 }, new String[][]{ Alert_VN.TASK_DES21, Alert_EN.TASK_DES21 }, new String[][]{ Alert_VN.TASK_DES22, Alert_EN.TASK_DES22 }, new short[]{ 50, 30, 20, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE7, Alert_EN.TASK_NOTE7 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 11, new String[]{ Alert_VN.TASK_23, Alert_EN.TASK_23 }, new String[]{ Alert_VN.TASK_24, Alert_EN.TASK_24 }, new String[][]{ Alert_VN.TASK_DES23, Alert_EN.TASK_DES23 }, new String[][]{ Alert_VN.TASK_DES24, Alert_EN.TASK_DES24 }, new short[]{ -1, 10, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE8, Alert_EN.TASK_NOTE8 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 12, new String[]{ Alert_VN.TASK_25, Alert_EN.TASK_25 }, new String[]{ Alert_VN.TASK_26, Alert_EN.TASK_26 }, new String[][]{ Alert_VN.TASK_DES25, Alert_EN.TASK_DES25 }, new String[][]{ Alert_VN.TASK_DES26, Alert_EN.TASK_DES26 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE9, Alert_EN.TASK_NOTE9 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 13, new String[]{ Alert_VN.TASK_27, Alert_EN.TASK_27 }, new String[]{ Alert_VN.TASK_28, Alert_EN.TASK_28 }, new String[][]{ Alert_VN.TASK_DES27, Alert_EN.TASK_DES27 }, new String[][]{ Alert_VN.TASK_DES28, Alert_EN.TASK_DES28 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE10, Alert_EN.TASK_NOTE10 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 14, new String[]{ Alert_VN.TASK_29, Alert_EN.TASK_29 }, new String[]{ Alert_VN.TASK_30, Alert_EN.TASK_30 }, new String[][]{ Alert_VN.TASK_DES29, Alert_EN.TASK_DES29 }, new String[][]{ Alert_VN.TASK_DES30, Alert_EN.TASK_DES30 }, new short[]{ -1, 40, 60, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE11, Alert_EN.TASK_NOTE11 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 15, new String[]{ Alert_VN.TASK_31, Alert_EN.TASK_31 }, new String[]{ Alert_VN.TASK_32, Alert_EN.TASK_32 }, new String[][]{ Alert_VN.TASK_DES31, Alert_EN.TASK_DES31 }, new String[][]{ Alert_VN.TASK_DES32, Alert_EN.TASK_DES32 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE12, Alert_EN.TASK_NOTE12 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 16, new String[]{ Alert_VN.TASK_33, Alert_EN.TASK_33 }, new String[]{ Alert_VN.TASK_34, Alert_EN.TASK_34 }, new String[][]{ Alert_VN.TASK_DES33, Alert_EN.TASK_DES33 }, new String[][]{ Alert_VN.TASK_DES34, Alert_EN.TASK_DES34 }, new short[]{ -1, 250, 250, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE13, Alert_EN.TASK_NOTE13 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 17, new String[]{ Alert_VN.TASK_35, Alert_EN.TASK_35 }, new String[]{ Alert_VN.TASK_36, Alert_EN.TASK_36 }, new String[][]{ Alert_VN.TASK_DES35, Alert_EN.TASK_DES35 }, new String[][]{ Alert_VN.TASK_DES36, Alert_EN.TASK_DES36 }, null, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 18, new String[]{ Alert_VN.TASK_37, Alert_EN.TASK_37 }, new String[]{ Alert_VN.TASK_38, Alert_EN.TASK_38 }, new String[][]{ Alert_VN.TASK_DES37, Alert_EN.TASK_DES37 }, new String[][]{ Alert_VN.TASK_DES38, Alert_EN.TASK_DES38 }, new short[]{ -1, 150, 150, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 19, new String[]{ Alert_VN.TASK_39, Alert_EN.TASK_39 }, new String[]{ Alert_VN.TASK_40, Alert_EN.TASK_40 }, new String[][]{ Alert_VN.TASK_DES39, Alert_EN.TASK_DES39 }, new String[][]{ Alert_VN.TASK_DES40, Alert_EN.TASK_DES40 }, new short[]{ -1, 50, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE14, Alert_EN.TASK_NOTE14 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 20, new String[]{ Alert_VN.TASK_41, Alert_EN.TASK_41 }, new String[]{ Alert_VN.TASK_42, Alert_EN.TASK_42 }, new String[][]{ Alert_VN.TASK_DES41, Alert_EN.TASK_DES41 }, new String[][]{ Alert_VN.TASK_DES42, Alert_EN.TASK_DES42 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE15, Alert_EN.TASK_NOTE15 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 21, new String[]{ Alert_VN.TASK_43, Alert_EN.TASK_43 }, new String[]{ Alert_VN.TASK_44, Alert_EN.TASK_44 }, new String[][]{ Alert_VN.TASK_DES43, Alert_EN.TASK_DES43 }, new String[][]{ Alert_VN.TASK_DES44, Alert_EN.TASK_DES44 }, new short[]{ -1, 100, 100, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 22, new String[]{ Alert_VN.TASK_45, Alert_EN.TASK_45 }, new String[]{ Alert_VN.TASK_46, Alert_EN.TASK_46 }, new String[][]{ Alert_VN.TASK_DES45, Alert_EN.TASK_DES45 }, new String[][]{ Alert_VN.TASK_DES46, Alert_EN.TASK_DES46 }, new short[]{ -1, 200, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE16, Alert_EN.TASK_NOTE16 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 23, new String[]{ Alert_VN.TASK_47, Alert_EN.TASK_47 }, new String[]{ Alert_VN.TASK_48, Alert_EN.TASK_48 }, new String[][]{ Alert_VN.TASK_DES47, Alert_EN.TASK_DES47 }, new String[][]{ Alert_VN.TASK_DES48, Alert_EN.TASK_DES48 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE17, Alert_EN.TASK_NOTE17 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 24, new String[]{ Alert_VN.TASK_49, Alert_EN.TASK_49 }, new String[]{ Alert_VN.TASK_50, Alert_EN.TASK_50 }, new String[][]{ Alert_VN.TASK_DES49, Alert_EN.TASK_DES49 }, new String[][]{ Alert_VN.TASK_DES50, Alert_EN.TASK_DES50 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE18, Alert_EN.TASK_NOTE18 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 25, new String[]{ Alert_VN.TASK_51, Alert_EN.TASK_51 }, new String[]{ Alert_VN.TASK_52, Alert_EN.TASK_52 }, new String[][]{ Alert_VN.TASK_DES51, Alert_EN.TASK_DES51 }, new String[][]{ Alert_VN.TASK_DES52, Alert_EN.TASK_DES52 }, new short[]{ -1, 500, 500, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 26, new String[]{ Alert_VN.TASK_53, Alert_EN.TASK_53 }, new String[]{ Alert_VN.TASK_54, Alert_EN.TASK_54 }, new String[][]{ Alert_VN.TASK_DES53, Alert_EN.TASK_DES53 }, new String[][]{ Alert_VN.TASK_DES54, Alert_EN.TASK_DES54 }, new short[]{ -1, 100, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 27, new String[]{ Alert_VN.TASK_55, Alert_EN.TASK_55 }, new String[]{ Alert_VN.TASK_56, Alert_EN.TASK_56 }, new String[][]{ Alert_VN.TASK_DES55, Alert_EN.TASK_DES55 }, new String[][]{ Alert_VN.TASK_DES56, Alert_EN.TASK_DES56 }, new short[]{ -1, 100, -1 }, null, null, new String[]{ Alert_VN.TASK_NOTE19, Alert_EN.TASK_NOTE19 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 28, new String[]{ Alert_VN.TASK_57, Alert_EN.TASK_57 }, new String[]{ Alert_VN.TASK_58, Alert_EN.TASK_58 }, new String[][]{ Alert_VN.TASK_DES57, Alert_EN.TASK_DES57 }, new String[][]{ Alert_VN.TASK_DES58, Alert_EN.TASK_DES58 }, new short[]{ -1, 500, 500, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 29, new String[]{ Alert_VN.TASK_59, Alert_EN.TASK_59 }, new String[]{ Alert_VN.TASK_60, Alert_EN.TASK_60 }, new String[][]{ Alert_VN.TASK_DES59, Alert_EN.TASK_DES59 }, new String[][]{ Alert_VN.TASK_DES60, Alert_EN.TASK_DES60 }, new short[]{ -1, 10, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 30, new String[]{ Alert_VN.TASK_61, Alert_EN.TASK_61 }, new String[]{ Alert_VN.TASK_62, Alert_EN.TASK_62 }, new String[][]{ Alert_VN.TASK_DES61, Alert_EN.TASK_DES61 }, new String[][]{ Alert_VN.TASK_DES62, Alert_EN.TASK_DES62 }, new short[]{ -1, 10, 1, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 31, new String[]{ Alert_VN.TASK_63, Alert_EN.TASK_63 }, new String[]{ Alert_VN.TASK_64, Alert_EN.TASK_64 }, new String[][]{ Alert_VN.TASK_DES63, Alert_EN.TASK_DES63 }, new String[][]{ Alert_VN.TASK_DES64, Alert_EN.TASK_DES64 }, new short[]{ -1, 200, 200, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 32, new String[]{ Alert_VN.TASK_65, Alert_EN.TASK_65 }, new String[]{ Alert_VN.TASK_66, Alert_EN.TASK_66 }, new String[][]{ Alert_VN.TASK_DES65, Alert_EN.TASK_DES65 }, new String[][]{ Alert_VN.TASK_DES66, Alert_EN.TASK_DES66 }, null, null, null, new String[]{ Alert_VN.TASK_NOTE20, Alert_EN.TASK_NOTE20 }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 33, new String[]{ Alert_VN.TASK_67, Alert_EN.TASK_67 }, new String[]{ Alert_VN.TASK_68, Alert_EN.TASK_68 }, new String[][]{ Alert_VN.TASK_DES67, Alert_EN.TASK_DES67 }, new String[][]{ Alert_VN.TASK_DES68, Alert_EN.TASK_DES68 }, new short[]{ -1, 250, 250, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 34, new String[]{ Alert_VN.TASK_69, Alert_EN.TASK_69 }, new String[]{ Alert_VN.TASK_70, Alert_EN.TASK_70 }, new String[][]{ Alert_VN.TASK_DES69, Alert_EN.TASK_DES69 }, new String[][]{ Alert_VN.TASK_DES70, Alert_EN.TASK_DES70 }, new short[]{ -1, 99, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 35, new String[]{ Alert_VN.TASK_71, Alert_EN.TASK_71 }, new String[]{ Alert_VN.TASK_72, Alert_EN.TASK_72 }, new String[][]{ Alert_VN.TASK_DES71, Alert_EN.TASK_DES71 }, new String[][]{ Alert_VN.TASK_DES72, Alert_EN.TASK_DES72 }, new short[]{ -1, 150, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 36, new String[]{ Alert_VN.TASK_73, Alert_EN.TASK_73 }, new String[]{ Alert_VN.TASK_74, Alert_EN.TASK_74 }, new String[][]{ Alert_VN.TASK_DES73, Alert_EN.TASK_DES73 }, new String[][]{ Alert_VN.TASK_DES74, Alert_EN.TASK_DES74 }, new short[]{ -1, 100, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 37, new String[]{ Alert_VN.TASK_75, Alert_EN.TASK_75 }, new String[]{ Alert_VN.TASK_76, Alert_EN.TASK_76 }, new String[][]{ Alert_VN.TASK_DES75, Alert_EN.TASK_DES75 }, new String[][]{ Alert_VN.TASK_DES76, Alert_EN.TASK_DES76 }, new short[]{ -1, 15, 5, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 38, new String[]{ Alert_VN.TASK_77, Alert_EN.TASK_77 }, new String[]{ Alert_VN.TASK_78, Alert_EN.TASK_78 }, new String[][]{ Alert_VN.TASK_DES77, Alert_EN.TASK_DES77 }, new String[][]{ Alert_VN.TASK_DES78, Alert_EN.TASK_DES78 }, new short[]{ -1, 100, 150, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 39, new String[]{ Alert_VN.TASK_79, Alert_EN.TASK_79 }, new String[]{ Alert_VN.TASK_80, Alert_EN.TASK_80 }, new String[][]{ Alert_VN.TASK_DES79, Alert_EN.TASK_DES79 }, new String[][]{ Alert_VN.TASK_DES80, Alert_EN.TASK_DES80 }, new short[]{ -1, 10, 10, 100, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 40, new String[]{ Alert_VN.TASK_81, Alert_EN.TASK_81 }, new String[]{ Alert_VN.TASK_82, Alert_EN.TASK_82 }, new String[][]{ Alert_VN.TASK_DES81, Alert_EN.TASK_DES81 }, new String[][]{ Alert_VN.TASK_DES82, Alert_EN.TASK_DES82 }, new short[]{ -1, 50, 15, 5, -1 }, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 41, new String[]{ Alert_VN.TASK_83, Alert_EN.TASK_83 }, new String[]{ Alert_VN.TASK_84, Alert_EN.TASK_84 }, new String[][]{ Alert_VN.TASK_DES83, Alert_EN.TASK_DES83 }, new String[][]{ Alert_VN.TASK_DES84, Alert_EN.TASK_DES84 }, null, null, null, new String[]{ "", "" }));
        ServerController.taskTemplates.add(new TaskTemplate((short) 42, new String[]{ Alert_VN.TASK_85, Alert_EN.TASK_85 }, new String[]{ Alert_VN.TASK_86, Alert_EN.TASK_86 }, new String[][]{ Alert_VN.TASK_DES85, Alert_EN.TASK_DES85 }, new String[][]{ Alert_VN.TASK_DES86, Alert_EN.TASK_DES86 }, new short[]{ -1, 30, -1 }, null, null, new String[]{ "", "" }));
    }
}
